document.addEventListener('DOMContentLoaded', () => {
    initCountdown();
    loadTimeline();
    loadNasaGallery();
});

// Countdown to next mission (e.g., Artemis III targeted for 2026/2027)
function initCountdown() {
    const targetDate = new Date("2026-11-01T00:00:00").getTime();
    
    const cdDays = document.getElementById('cd-days');
    const cdHours = document.getElementById('cd-hours');
    const cdMins = document.getElementById('cd-mins');
    
    function update() {
        const now = new Date().getTime();
        const distance = targetDate - now;
        
        if (distance < 0) {
            cdDays.innerText = "00";
            cdHours.innerText = "00";
            cdMins.innerText = "00";
            return;
        }
        
        const days = Math.floor(distance / (1000 * 60 * 60 * 24));
        const hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        const minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
        
        cdDays.innerText = days.toString().padStart(2, '0');
        cdHours.innerText = hours.toString().padStart(2, '0');
        cdMins.innerText = minutes.toString().padStart(2, '0');
    }
    
    update();
    setInterval(update, 60000); // update every minute
}

// Load static timeline history generated by GitHub Actions
async function loadTimeline() {
    const container = document.getElementById('timeline-container');
    
    try {
        const response = await fetch('data/timeline.json');
        if (!response.ok) throw new Error('Timeline data not found');
        const data = await response.json();
        
        container.innerHTML = ''; // Clear loading state
        
        data.forEach((item, index) => {
            const side = index % 2 === 0 ? 'left' : 'right';
            const element = document.createElement('div');
            element.className = `timeline-item ${side}`;
            
            const content = document.createElement('div');
            content.className = 'timeline-content';
            
            content.innerHTML = `
                <div class="timeline-date">${formatDate(item.date)}</div>
                <h3>${item.title}</h3>
                <p>${item.description}</p>
                ${item.imageUrl ? `<img src="${item.imageUrl}" alt="${item.title}" loading="lazy" />` : ''}
            `;
            
            element.appendChild(content);
            container.appendChild(element);
        });
        
    } catch (error) {
        console.error("Error loading timeline:", error);
        container.innerHTML = `<div class="loading-state">Історія оновлюється. Дані поки недоступні.</div>`;
    }
}

// Helper to format Date: YYYY-MM-DD -> DD Місяць YYYY
function formatDate(dateString) {
    const options = { year: 'numeric', month: 'long', day: 'numeric' };
    const date = new Date(dateString);
    return date.toLocaleDateString('uk-UA', options);
}

// Fetch live images from NASA API
async function loadNasaGallery() {
    const container = document.getElementById('gallery-container');
    const apiUrl = 'https://images-api.nasa.gov/search?q=Artemis&media_type=image';
    
    try {
        const response = await fetch(apiUrl);
        const data = await response.json();
        
        // Get the latest 9 items
        const items = data.collection.items.slice(0, 9);
        
        container.innerHTML = ''; // Clear loading
        
        items.forEach(item => {
            try {
                const title = item.data[0].title;
                const thumbUrl = item.links[0].href;
                
                const galleryItem = document.createElement('div');
                galleryItem.className = 'gallery-item';
                
                galleryItem.innerHTML = `
                    <img src="${thumbUrl}" alt="${title}" loading="lazy"/>
                    <div class="gallery-overlay">
                        <h4>${title}</h4>
                    </div>
                `;
                
                container.appendChild(galleryItem);
            } catch (e) {
                // skip items without thumbnails
            }
        });
        
    } catch (error) {
        console.error("Error loading NASA gallery:", error);
        container.innerHTML = `<div class="loading-state">Сталася помилка при завантаженні галереї NASA. Перевірте підключення до мережі.</div>`;
    }
}
