document.addEventListener('DOMContentLoaded', () => {
    initCountdown();
    loadTimeline();
    loadNasaGallery();
    initTracker();
    loadNasaNews();
    loadWeather();
});

// Simulate real-time tracker data bounds
function initTracker() {
    let speed = 39400; // km/h
    let dist = 384400; // km
    
    const speedEl = document.getElementById('tk-speed');
    const distEl = document.getElementById('tk-dist');
    const trajEl = document.getElementById('tk-traj');
    
    if (!speedEl || !distEl || !trajEl) return;
    
    setInterval(() => {
        speed += (Math.random() - 0.5) * 50;
        dist -= (Math.random() - 0.2) * 10;
        
        speedEl.innerText = Math.floor(speed).toLocaleString() + ' км/год';
        distEl.innerText = Math.floor(dist).toLocaleString() + ' км';
        trajEl.innerText = 'Орбітальна стабілізація';
    }, 2000);
}

// Countdown to next mission (e.g., Artemis III targeted for 2026/2027)
function initCountdown() {
    const targetDate = new Date("2026-11-01T00:00:00").getTime();
    
    const cdDays = document.getElementById('cd-days');
    const cdHours = document.getElementById('cd-hours');
    const cdMins = document.getElementById('cd-mins');
    
    function update() {
        const now = new Date().getTime();
        const distance = targetDate - now;
        
        if (distance < 0) {
            cdDays.innerText = "00";
            cdHours.innerText = "00";
            cdMins.innerText = "00";
            return;
        }
        
        const days = Math.floor(distance / (1000 * 60 * 60 * 24));
        const hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        const minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
        
        cdDays.innerText = days.toString().padStart(2, '0');
        cdHours.innerText = hours.toString().padStart(2, '0');
        cdMins.innerText = minutes.toString().padStart(2, '0');
    }
    
    update();
    setInterval(update, 60000); // update every minute
}

// Render timeline data
function renderTimelineData(data) {
    const container = document.getElementById('timeline-container');
    container.innerHTML = '';
    
    data.forEach((item, index) => {
        const side = index % 2 === 0 ? 'left' : 'right';
        const element = document.createElement('div');
        element.className = `timeline-item ${side}`;
        
        const content = document.createElement('div');
        content.className = 'timeline-content';
        
        content.innerHTML = `
            <div class="timeline-date">${formatDate(item.date)}</div>
            <h3>${item.title}</h3>
            <p>${item.description}</p>
        `;
        
        element.appendChild(content);
        container.appendChild(element);
    });
}

// Load static timeline history generated by GitHub Actions
async function loadTimeline() {
    const defaultData = [
      {
        "date": "2022-11-16",
        "title": "Artemis I - Запуск",
        "description": "Перший непілотований випробувальний політ ракети SLS та корабля Orion."
      },
      {
        "date": "2022-12-11",
        "title": "Artemis I - Повернення",
        "description": "Космічний корабель Orion успішно приводнився в Тихому океані після 25-денної місії навколо Місяця."
      },
      {
        "date": "2023-04-03",
        "title": "Artemis II - Оголошення екіпажу",
        "description": "NASA та Канадське космічне агентство оголосили імена чотирьох астронавтів, які першими облетять Місяць за понад 50 років."
      },
      {
        "date": "2026-04-01",
        "title": "Artemis II - Запуск",
        "description": "Космічний корабель Orion з чотирма астронавтами на борту успішно стартував за допомогою потужної ракети SLS. Екіпаж вирушив у історичну місію обльоту Місяця."
      }
    ];

    try {
        const response = await fetch('data/timeline.json');
        if (!response.ok) throw new Error('Timeline data not found');
        const data = await response.json();
        renderTimelineData(data);
    } catch (error) {
        console.warn("Could not fetch timeline.json (likely CORS), using fallback data.", error);
        renderTimelineData(defaultData);
    }
}

// Helper to format Date: YYYY-MM-DD -> DD Місяць YYYY
function formatDate(dateString) {
    const options = { year: 'numeric', month: 'long', day: 'numeric' };
    const date = new Date(dateString);
    return date.toLocaleDateString('uk-UA', options);
}

// Fetch live images from NASA API
async function loadNasaGallery() {
    const container = document.getElementById('gallery-container');
    const apiUrl = 'https://images-api.nasa.gov/search?q=Artemis%20II&media_type=image';
    
    try {
        const response = await fetch(apiUrl);
        const data = await response.json();
        
        // Get the latest 24 items
        const items = data.collection.items.slice(0, 24);
        
        container.innerHTML = ''; // Clear loading
        
        items.forEach(item => {
            try {
                const title = item.data[0].title;
                const thumbUrl = item.links[0].href;
                
                const galleryItem = document.createElement('div');
                galleryItem.className = 'gallery-item';
                
                galleryItem.innerHTML = `
                    <img src="${thumbUrl}" alt="${title}" loading="lazy" onclick="openModal('${thumbUrl}')"/>
                `;
                
                container.appendChild(galleryItem);
            } catch (e) {
                // skip items without thumbnails
            }
        });
        
    } catch (error) {
        console.error("Error loading NASA gallery:", error);
        container.innerHTML = `<div class="loading-state">Сталася помилка при завантаженні галереї NASA. Перевірте підключення до мережі.</div>`;
    }
}

// Modal functions for gallery
function openModal(imgUrl) {
    let modal = document.getElementById('image-modal');
    if (!modal) {
        modal = document.createElement('div');
        modal.id = 'image-modal';
        modal.className = 'modal glassmorphism';
        modal.innerHTML = `
            <span class="close-modal" onclick="closeModal()">&times;</span>
            <img id="modal-img" src="" alt="Enlarged image" />
        `;
        document.body.appendChild(modal);
    }
    document.getElementById('modal-img').src = imgUrl;
    modal.style.display = 'flex';
}

function closeModal() {
    const modal = document.getElementById('image-modal');
    if (modal) {
        modal.style.display = 'none';
    }
}

// Load NASA RSS News
async function loadNasaNews() {
    const container = document.getElementById('news-container');
    const rssUrl = encodeURIComponent('https://www.nasa.gov/feed/');
    const apiUrl = `https://api.rss2json.com/v1/api.json?rss_url=${rssUrl}`;
    
    try {
        const response = await fetch(apiUrl);
        const data = await response.json();
        
        if (data.status !== "ok") throw new Error("RSS parse failed");
        
        container.innerHTML = '';
        const items = data.items.slice(0, 4);
        
        items.forEach(item => {
            const date = new Date(item.pubDate).toLocaleDateString('uk-UA');
            container.innerHTML += `
                <div class="news-item">
                    <div class="news-date">${date}</div>
                    <h4><a href="${item.link}" target="_blank">${item.title}</a></h4>
                </div>
            `;
        });
        
    } catch (error) {
        console.error("News error:", error);
        container.innerHTML = `<p class="loading-state">Не вдалося завантажити новини.</p>`;
    }
}

// Load Space Weather (NOAA Kp index)
async function loadWeather() {
    const container = document.getElementById('weather-container');
    const apiUrl = 'https://services.swpc.noaa.gov/products/noaa-planetary-k-index.json';
    
    try {
        const response = await fetch(apiUrl);
        const data = await response.json();
        
        // Data is an array of objects: {time_tag, Kp, a_running, station_count}
        // Get the latest observation
        const latest = data[data.length - 1];
        const kpIndex = parseFloat(latest.Kp);
        
        // Determine status based on Kp index scale
        let icon = '🌌';
        let status = 'Спокійно';
        let color = 'var(--text-primary)';
        
        if (kpIndex >= 5) {
            icon = '⚠️';
            status = 'Геомагнітна буря (G' + (Math.floor(kpIndex) - 4) + ')';
            color = '#ff4a4a';
        } else if (kpIndex >= 4) {
            icon = '⚡';
            status = 'Обурене поле';
            color = '#ffcc00';
        }
        
        container.innerHTML = `
            <div class="weather-icon">${icon}</div>
            <div class="weather-temp" style="color: ${color}">Kp ${kpIndex.toFixed(2)}</div>
            <p>Стан магнітосфери: <strong>${status}</strong></p>
            <div class="weather-details">
                <span>Оновлено: ${new Date(latest.time_tag).toLocaleTimeString('uk-UA')}</span>
            </div>
        `;
    } catch (error) {
        console.error("Space Weather error:", error);
        container.innerHTML = `<p class="loading-state">Дані про космічну погоду тимчасово недоступні.</p>`;
    }
}
